version: "3.8"

services:
  app:
    image: duonghieu1810/eatzy_backend:latest
    container_name: eatzy_backend_app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mariadb://10.200.30.250:3306/fooddelivery
      - DB_USERNAME=eatzy
      - DB_PASSWORD=eatzy
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_TOKEN_VALIDITY=${JWT_ACCESS_TOKEN_VALIDITY}
      - JWT_REFRESH_TOKEN_VALIDITY=${JWT_REFRESH_TOKEN_VALIDITY}
      - UPLOAD_FILE_BASE_URI=file:///app/upload/
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - VNPAY_TMN_CODE=${VNPAY_TMN_CODE}
      - VNPAY_HASH_SECRET=${VNPAY_HASH_SECRET}
      - VNPAY_URL=${VNPAY_URL}
      - APP_BASE_URL=${APP_BASE_URL}
      - MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}\
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./upload:/app/upload
    restart: always
